### PR TITLE
Demo app with use cases

### PR DESCRIPTION
**Pull request by WieFel**
Works on #7 and #12.

### CODE REVIEW

**Comment by daadu** [comment]
@WieFel #34 is for future as of now we do not support it. We will start working on it after #5 is completed.

**Comment by WieFel** [comment]
Oh, ok!

**Comment by WieFel** [comment]
@daadu From my side the demo app should be ready now!
The use cases are not too detailed but show the basic backdrop usages of the MDG. I also tried to include (almost) all functionalities like `subHeader` and `stickyFrontLayer`.

Please check out the pull request and try it yourself. To build it for the web, follow the steps here: https://flutter.dev/docs/get-started/web.

Any changes/suggestions are welcome ;)

**Comment by WieFel** [comment]
One tiny thing left: I still have to change the launcher icon...

**Comment by daadu** [comment]
Good job @WieFel !

I will review it this weekend.

**Comment by daadu** [comment]
This feature has landed in `v0.4.3`.

**Pull request merged**
