### PR TITLE
style: fix all lint issues

### PR DESCRIPTION
**Pull request by daadu**

### CODE REVIEW

**Comment by daadu** [comment]
@WieFel Could replace the current "analyze" action with one that fails it the linter rules are not followed. Current one count the "pub score". What do you think?

This package needs a breather - haven't touched it for a while. Will start with fixing all lint issues - check #100.

**Comment by daadu** [comment]
@WieFel All lint are fixed -  except "deprecation" ones.

**Comment by daadu** [comment]
> @daadu i think it would be also at the time to remove deprecated stuff. What do you think?

Yes, will file new PR for it. Also need to move all source files to `/src`.

**Comment by daadu** [comment]
@WieFel Did you completed the review for this PR?

**Review by WieFel — APPROVED** [review]

**Pull request merged**
