### PR TITLE
Backdrop scaffoldkey 

### PR DESCRIPTION
**Pull request by kannel-outis**
Included a scaffoldkey incase one needs to access let's say a snackbar or the bottomsheet of the backdrop scaffold to avoid creating multiple scaffolds :)

### CODE REVIEW

**Comment by WieFel** [comment]
Thanks for the contribution.
I am not sure whether we need an additional property `backDropScaffoldKey` as we already have the `Key key` inside the constructor of `BackdropScaffold`. That `key` is then passed to `super(key: key)`, which means it is used for the `BackdropScaffold` instance.

Maybe we could use the same `key` in
```dart
    return WillPopScope(
      onWillPop: () => _willPopCallback(context),
      child: Scaffold(
        key: scaffoldKey,
        key: widget.key ?? scaffoldKey,
```
Or do we need an extra property `backDropScaffoldKey` for that?
@daadu @kannel-outis what do you think?

**Comment by kannel-outis** [comment]
OMG I never really checked for the "key"(I needed it so badly that I had to add it) . Yes the `key` can be used instead of `backdropScaffoldKey`.

**Comment by WieFel** [comment]
But does it make a difference if we pass it to ```Scaffold(key : key, ...)``` or not?

**Comment by kannel-outis** [comment]
No it does not and really sorry for making this PR. I should have checked.

**Comment by daadu** [comment]
@kannel-outis `key` property is a recent feature update. You must have tried on the older version earlier, that is why missed it!!

**Comment by daadu** [comment]
@WieFel `key` property of any widget is for that widget itself, we shouldn't use it for other widget (might upset flutter!!), instead additional key like `scaffoldKey` could be added for `Scaffold` widget.

I suggest adding `scaffoldKey` to `BackdropScaffold` which could be used with `Scaffold` widget if provided, else create a `GlobalKey`. This can help to get underlying `ScaffoldState` without needing `BuildContext` (as of now user can do it by, `Backdrop.of(context).scaffoldKey`).

I saw similar patter in `MaterialApp` widget they have provided `navigatorKey` option - so that `BuildContext` could be avoided to access `NavigatorState`.

**Comment by daadu** [comment]
@WieFel or @kannel-outis I suggest file new PR for this.

**Comment by kannel-outis** [comment]
> @kannel-outis `key` property is a recent feature update. You must have tried on the older version earlier, that is why missed it!!

Maybe

**Comment by kannel-outis** [comment]
> @WieFel or @kannel-outis I suggest file new PR for this.

Ok

**Pull request closed without merging**
