### PR TITLE
Demo automatic deployment on tag creation

### PR DESCRIPTION
**Pull request by WieFel**
Added github action for demo web deployment.

### CODE REVIEW

**Comment by WieFel** [comment]
@daadu action is triggered on tag creation.
Is that ok? From now on we could create release tag for every new version we release to pub. Then, demo web deployment is triggered.

**Comment by daadu** [comment]
@WieFel, Fine will create tags for releases.

**Review by daadu — APPROVED** [review]
LGTM

**Comment by daadu** [comment]
This has landed with [v0.5.0 on pub.dev](https://pub.dev/packages/backdrop/versions/0.5.0).

**Pull request merged**
