### PR TITLE
refactor - making `BackdropScaffoldState` class public

### LINKED ISSUE #31: make _BackdropScaffoldState public and document it
- [x] make `_BackdropScaffoldState` public
- [x] members to be documented
  - [x] `AnimationController get controller`
  - [x] `bool get isBackLayerConcealed`
  - [x] `bool get isBackLayerRevealed`
  - [x] `void fling()`
  - [x] `void revealBackLayer()`
  - [x] `void concealBackLayer()`

### PR DESCRIPTION
**Pull request by daadu**
Closes #31

### CODE REVIEW

**Comment by daadu** [comment]
@WieFel I have made the class public. Request you to complete the documentation as discussed in #31

**Comment by WieFel** [comment]
Documented the members mentioned in #31.

`scaffoldKey` is still public. But I think it could be made private?

Also there is `getPanelAnimation()` which is public. Not sure whether this also should be made private?
@daadu

**Comment by daadu** [comment]
> `scaffoldKey` is still public. But I think it could be made private?
`scaffoldKey` is public if some user want to access the underlying scaffold to - show snackbar or somethings like that. It can be done by using `Backdrop.of(context).scaffoldKey.currentState.showSnackBar(...)`
> 
> Also there is `getPanelAnimation()` which is public. Not sure whether this also should be made private?
this should be made private

**Comment by WieFel** [comment]
@daadu done!

**Comment by daadu** [comment]
This feature has landed in `v0.4.1` on pub.dev.

**Pull request merged**
