### PR TITLE
Feature/reveal back layer at start

### LINKED ISSUE #80: Show backLayer first
**Is your feature request related to a problem? Please describe.**
I'm trying to reveal backLayer first, without use it as frontLayer, in order to mantain frontLayer controllers (eg. like in spotify, where frontLayer is music bottomBar, which on click goes to music controls, that we use in frontLayer

**Describe the solution you'd like**
I'd like a solution as "toggleFirst: true/false"

### PR DESCRIPTION
**Pull request by WieFel**
- Added property `revealBackLayerAtStart` to `BackdropScaffold`
- Renamed occurrences of `controller` to `animationController`

Closes #80

### CODE REVIEW

**Comment by daadu** [comment]
`controller` should be backward compatible.

**Comment by WieFel** [comment]
@daadu how do we do that? Have 2 properties at a time, `controller` (marked as deprecated) and `animationController`?

**Comment by daadu** [comment]
@WieFel I have added a commit for backward compatibility.

**Review by daadu — APPROVED** [review]
LGTM now.

**Comment by daadu** [comment]
This feature has landed with [v0.5.2 on pub.dev](https://pub.dev/packages/backdrop/versions/0.5.2).

**Pull request merged**
